import type {Metadata} from "next"
import {Geist_Mono} from "next/font/google"
import localFont from "next/font/local"

import "./globals.css"
import {ConvexAuthNextjsServerProvider} from "@convex-dev/auth/nextjs/server"
import {SignOutButton} from "@/app/components/sign-out-button"
import ConvexClientProvider from "@/components/ConvexClientProvider"
import {Toaster} from "@/components/ui/sonner"

const martianGrotesk = localFont({
	src: "./fonts/MartianGrotesk.woff2",
	variable: "--font-martian-grotesk",
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	icons: {
		icon: "/convex.svg",
	},
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ConvexAuthNextjsServerProvider>
			<html lang="en" className="h-full">
				<body
					className={`${martianGrotesk.variable} ${geistMono.variable} antialiased h-full`}
				>
					<ConvexClientProvider>
						<div className="flex flex-col items-center justify-center h-full w-full gap-8">
							<header className="p-8 flex flex-row items-center justify-end w-full min-h-[101px]">
								<SignOutButton />
							</header>
							{children}
						</div>
						<Toaster />
					</ConvexClientProvider>
				</body>
			</html>
		</ConvexAuthNextjsServerProvider>
	)
}
